# Generated by Django 5.0.1 on 2024-01-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publishedDate', models.DateField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
